CREATE USER 'BOOKSQL'@'localhost' IDENTIFIED BY 'BOOKSQLPWD';

GRANT ALL PRIVILEGES
ON '*'
TO 'BOOKSQL'@'localhost'
WITH GRANT OPTION;

SELECT 12*3;

-- 定义一个索引
CREATE INDEX PENALTIES_AMOUNT ON
PENALTIES (AMOUNT);

-- 创建视图
CREATE VIEW NUMBER_SETS (MATCHNO,DIFFERENCE) AS 
SELECT MATCHNO,ABS(WON-LOST)
FROM MATCHES;

-- 获取视图数据
SELECT * 
FROM NUMBER_SETS;

-- 用户和数据安全
GRANT SELECT
ON PLAYERS
TO DIANE;

GRANT SELECT,UPDATE
ON PLAYERS
TO PAUL;

GRANT SELECT,UPDATE
ON TEAMS
TO PAUL;

-- 删除表
DROP TABLE MATCHES;
-- 删除视图
DROP VIEW NUMBER_SETS;
-- 删除索引
DROP INDEX PENALTIES_AMOUNT;

-- 系统变量
-- 查看MYSQL的版本。在系统变量前加两个@，就会返回它的值。
SELECT @@VERSION;
-- 与此有相同效果的语句
SELECT VERSION();
-- 改变系统变量的值
SET @@SQL_MODE = 'PIPES_AS_CONCAT';

-- 列的描述性数据
SHOW COLUMNS FROM PLAYERS;
-- 索引的描述性数据
SHOW INDEX FROM PENALTIES;
-- OTHER
SHOW DATABASES;
SHOW TABLES;
SHOW CREATE TABLE PLAYERS;
SHOW GRANTS FOR BOOKSQL@localhost;
SHOW PRIVILEGES;

-- 获取错误信息
SHOW WARNINGS;
SHOW ERRORS;
SHOW COUNT(*) WARNINGS;

-- 获取TIME_ZONE系统变量的值
SELECT @@TIME_ZONE;

SELECT TRUE,FALSE;

