-- partition
CREATE DATABASE studySQL DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE studySQL;

SET NAMES utf8;

CREATE TABLE part
(
	-- id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	
	num INT NOT NULL DEFAULT 0
)
PARTITION BY RANGE(num)
(
	PARTITION p0 VALUES LESS THAN(10),
	PARTITION p1 VALUES LESS THAN(20),
	PARTITION p2 VALUES LESS THAN(30),
	PARTITION p3 VALUES LESS THAN MAXVALUE
);
-- )ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO part VALUES (1);
INSERT INTO part VALUES (2);
INSERT INTO part VALUES (3);
INSERT INTO part VALUES (8);
INSERT INTO part VALUES (18);


ALTER TABLE part DROP PARTITION p0;